# Generated by Django 5.2.17 on 2026-10-09 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("openbible_id", models.CharField(max_length=16, unique=True)),
                ("slug", models.SlugField(max_length=80)),
                ("name", models.CharField(db_index=True, max_length=120)),
                (
                    "name_pl",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("kind", models.CharField(blank=True, max_length=16)),
                ("types", models.JSONField(blank=True, default=list)),
                ("wikidata", models.CharField(blank=True, max_length=24)),
                ("verse_count", models.PositiveIntegerField(default=0)),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "miejsce",
                "verbose_name_plural": "miejsca",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlaceLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("modern_id", models.CharField(blank=True, max_length=16)),
                ("name", models.CharField(max_length=160)),
                ("lon", models.FloatField()),
                ("lat", models.FloatField()),
                ("geometry", models.CharField(default="point", max_length=16)),
                ("radius_m", models.PositiveIntegerField(blank=True, null=True)),
                ("type", models.CharField(blank=True, max_length=40)),
                ("score", models.IntegerField(default=0)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "ordering": ["place", "order"],
                "unique_together": {("place", "order")},
            },
        ),
        migrations.CreateModel(
            name="PlaceRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.PositiveIntegerField(db_index=True)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refs",
                        to="places.place",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ordinal", "place"],
                        name="places_plac_ordinal_6c2c28_idx",
                    )
                ],
                "unique_together": {("place", "ordinal")},
            },
        ),
    ]
