# Generated by Django 6.1.1 on 2026-09-22 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "osis",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("order", models.PositiveSmallIntegerField(unique=True)),
                (
                    "testament",
                    models.CharField(
                        choices=[("OT", "Stary Testament"), ("NT", "Nowy Testament")],
                        max_length=2,
                    ),
                ),
                ("abbr", models.CharField(max_length=8, verbose_name="skrót BT")),
                (
                    "name_pl",
                    models.CharField(max_length=64, verbose_name="nazwa polska"),
                ),
                ("deuterocanonical", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "księga",
                "verbose_name_plural": "księgi",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("language", models.CharField(max_length=8)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("original", "tekst oryginalny"),
                            ("translation", "przekład"),
                        ],
                        max_length=16,
                    ),
                ),
                ("versification", models.CharField(default="mt", max_length=16)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("license", models.CharField(blank=True, max_length=128)),
                ("source_url", models.URLField(blank=True)),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("open", "otwarte (wolna licencja / domena publiczna)"),
                            ("licensed", "za zgodą właściciela praw"),
                            ("private", "tylko prywatnie (użytek własny)"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "dzieło",
                "verbose_name_plural": "dzieła",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter", models.PositiveSmallIntegerField()),
                ("verse", models.PositiveSmallIntegerField()),
                ("ordinal", models.PositiveIntegerField(db_index=True, unique=True)),
                ("osis_id", models.CharField(max_length=24, unique=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verses",
                        to="corpus.book",
                    ),
                ),
            ],
            options={
                "verbose_name": "werset",
                "verbose_name_plural": "wersety",
                "ordering": ["ordinal"],
            },
        ),
        migrations.CreateModel(
            name="VerseText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("text_norm", models.TextField(blank=True)),
                (
                    "verse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texts",
                        to="corpus.verse",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="texts",
                        to="corpus.work",
                    ),
                ),
            ],
            options={
                "verbose_name": "tekst wersetu",
                "verbose_name_plural": "teksty wersetów",
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("surface", models.CharField(max_length=64)),
                ("surface_norm", models.CharField(db_index=True, max_length=64)),
                ("lemma", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "lemma_norm",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("strong", models.CharField(blank=True, db_index=True, max_length=12)),
                ("morph", models.CharField(blank=True, max_length=32)),
                ("pos", models.CharField(blank=True, max_length=8)),
                ("prefixes", models.CharField(blank=True, max_length=16)),
                (
                    "verse_text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="corpus.versetext",
                    ),
                ),
            ],
            options={
                "verbose_name": "token",
                "verbose_name_plural": "tokeny",
                "ordering": ["verse_text", "position"],
            },
        ),
        migrations.AddConstraint(
            model_name="verse",
            constraint=models.UniqueConstraint(
                fields=("book", "chapter", "verse"), name="uniq_verse_addr"
            ),
        ),
        migrations.AddConstraint(
            model_name="token",
            constraint=models.UniqueConstraint(
                fields=("verse_text", "position"), name="uniq_token_pos"
            ),
        ),
        migrations.AddIndex(
            model_name="versetext",
            index=models.Index(
                fields=["work", "verse"], name="corpus_vers_work_id_2626c2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="versetext",
            constraint=models.UniqueConstraint(
                fields=("verse", "work"), name="uniq_versetext"
            ),
        ),
    ]
