# Generated by Django 6.1.1 on 2026-09-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0002_fts_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="access",
            field=models.CharField(
                choices=[
                    ("open", "otwarte (wolna licencja / domena publiczna)"),
                    ("licensed", "za zgodą właściciela praw"),
                    ("private", "tylko prywatnie (użytek własny)"),
                    (
                        "personal",
                        "osobisty (materiał użytkownika, widoczny tylko dla niego)",
                    ),
                ],
                default="open",
                max_length=16,
            ),
        ),
    ]
