# Generated by Django 6.1.1 on 2026-09-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0003_alter_work_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lexeme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strong", models.CharField(max_length=12, unique=True)),
                ("language", models.CharField(max_length=3)),
                ("lemma", models.CharField(max_length=64)),
                ("lemma_norm", models.CharField(db_index=True, max_length=64)),
                ("transliteration", models.CharField(blank=True, max_length=64)),
                ("morph", models.CharField(blank=True, max_length=24)),
                ("gloss", models.CharField(blank=True, max_length=200)),
                ("meaning", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["strong"],
            },
        ),
    ]
