# Generated by Django 6.1.1 on 2026-09-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0004_lexeme"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerseLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_ordinal", models.PositiveIntegerField(db_index=True)),
                ("to_start", models.PositiveIntegerField()),
                ("to_end", models.PositiveIntegerField()),
                ("votes", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["from_ordinal", "-votes"],
                "indexes": [
                    models.Index(
                        fields=["from_ordinal", "-votes"],
                        name="corpus_vers_from_or_71236a_idx",
                    )
                ],
            },
        ),
    ]
