# Generated by Django 6.1.1 on 2026-09-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("corpus", "0005_verselink"),
    ]

    operations = [
        migrations.AddField(
            model_name="lexeme",
            name="translit_fold",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
