# Generated by Django 6.1.1 on 2026-09-23 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AneText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(default="ebl", max_length=16)),
                ("source_id", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("name_pl", models.CharField(blank=True, max_length=200)),
                ("language", models.CharField(default="akk", max_length=8)),
                ("intro", models.TextField(blank=True)),
                ("license", models.CharField(blank=True, max_length=200)),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("source", "source_id")},
            },
        ),
        migrations.CreateModel(
            name="AneChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(blank=True, max_length=64)),
                ("name", models.CharField(max_length=32)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(blank=True, max_length=300)),
                (
                    "text",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="ane.anetext",
                    ),
                ),
            ],
            options={
                "ordering": ["text", "order"],
                "unique_together": {("text", "stage", "name")},
            },
        ),
        migrations.CreateModel(
            name="AneLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("number", models.CharField(max_length=16)),
                ("normalized", models.TextField(blank=True)),
                ("translation_en", models.TextField(blank=True)),
                ("translation_pl", models.TextField(blank=True)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="ane.anechapter",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter", "order"],
                "unique_together": {("chapter", "order")},
            },
        ),
        migrations.CreateModel(
            name="AnePassage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("line_start", models.CharField(max_length=16)),
                ("line_end", models.CharField(max_length=16)),
                ("normalized", models.TextField(blank=True)),
                ("translation_en", models.TextField()),
                ("translation_pl", models.TextField(blank=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passages",
                        to="ane.anechapter",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter", "order"],
                "unique_together": {("chapter", "order")},
            },
        ),
    ]
