# Generated by Django 6.1.1 on 2026-09-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PatWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("series", models.CharField(max_length=8)),
                ("volume", models.PositiveSmallIntegerField()),
                ("ccel_id", models.CharField(max_length=32)),
                ("author", models.CharField(max_length=120)),
                ("author_pl", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=300)),
                ("title_pl", models.CharField(blank=True, max_length=300)),
                ("url", models.URLField(blank=True)),
                (
                    "license",
                    models.CharField(
                        default="domena publiczna (przekład XIX w.; CCEL)",
                        max_length=120,
                    ),
                ),
            ],
            options={
                "ordering": ["series", "volume", "id"],
                "unique_together": {("ccel_id", "author", "title")},
            },
        ),
        migrations.CreateModel(
            name="PatPassage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("section", models.CharField(blank=True, max_length=300)),
                ("page", models.CharField(blank=True, max_length=16)),
                ("text_en", models.TextField()),
                ("text_pl", models.TextField(blank=True)),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passages",
                        to="patristics.patwork",
                    ),
                ),
            ],
            options={
                "ordering": ["work", "order"],
                "unique_together": {("work", "order")},
            },
        ),
        migrations.CreateModel(
            name="PatRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.PositiveIntegerField(db_index=True)),
                ("end", models.PositiveIntegerField()),
                (
                    "passage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refs",
                        to="patristics.patpassage",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["start", "end"], name="patristics__start_0b8897_idx"
                    )
                ],
            },
        ),
    ]
